import { initialize, render } from "./main.tsx";
// TODO load this from @curvenote/renderers
import { AnyModel } from "./model.ts";

initialize(); // Call the initialize function
const sequence = new AnyModel({});

const fromFile = new AnyModel({
  annotations: [
    {
      direction: 1,
      end: 118,
      name: "BB seq FOR",
      start: 94,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 296,
      name: "upstream anneal",
      start: 268,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 316,
      name: "20bp random sequence",
      start: 296,
      type: "misc_feature",
    },
    {
      direction: -1,
      end: 343,
      name: "downstream anneal",
      start: 316,
      type: "misc_feature",
    },
    {
      direction: -1,
      end: 505,
      name: "pOpen ori anneal REV",
      start: 476,
      type: "misc_feature",
    },
    {
      direction: -1,
      end: 1343,
      name: "AmpR",
      start: 482,
      type: "CDS",
    },
    {
      direction: -1,
      end: 523,
      name: "BB seq REV",
      start: 501,
      type: "misc_feature",
    },
    {
      direction: -1,
      end: 1448,
      name: "AmpR promoter",
      start: 1343,
      type: "promoter",
    },
    {
      direction: 1,
      end: 1463,
      name: "AarI",
      start: 1448,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 1480,
      name: "M13 fwd",
      start: 1463,
      type: "primer_bind",
    },
    {
      direction: 1,
      end: 1512,
      name: "tonB terminator",
      start: 1480,
      type: "terminator",
    },
    {
      direction: -1,
      end: 1528,
      name: "SLiCE-rev",
      start: 1508,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 1528,
      name: "BioBrick prefix",
      start: 1527,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 1552,
      name: "Barcode A",
      start: 1532,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 1590,
      name: "Barcode",
      start: 1532,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 2475,
      name: "pT7-UTR1-plamGFP-tT7hyb6",
      start: 1532,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 1570,
      name: "Barcode Cut (I-SceI)",
      start: 1552,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 1590,
      name: "Barcode B",
      start: 1570,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 1610,
      name: "Dialout Forward [49]",
      start: 1590,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 1621,
      name: "CAST 0 [TAAC]",
      start: 1610,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 1641,
      name: "pT7",
      start: 1621,
      type: "primer_bind",
    },
    {
      direction: 1,
      end: 1669,
      name: "UTR1",
      start: 1641,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 1675,
      name: "BsaI_Bind",
      start: 1669,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 1677,
      name: "MC0U-SP",
      start: 1669,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 2367,
      name: "plamGFP",
      start: 1677,
      type: "CDS",
    },
    {
      direction: 1,
      end: 2385,
      name: "CDS Suffix",
      start: 2367,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 2424,
      name: "T7hyb6 Terminator",
      start: 2385,
      type: "regulatory",
    },
    {
      direction: 1,
      end: 2435,
      name: "CAST 0 [GGAG]",
      start: 2424,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 2455,
      name: "Dialout Reverse [0]",
      start: 2435,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 2475,
      name: "Terminator Spacer",
      start: 2455,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 2482,
      name: "BioBrick suffix",
      start: 2478,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 2497,
      name: "SLiCE-for",
      start: 2478,
      type: "misc_feature",
    },
    {
      direction: -1,
      end: 2516,
      name: "T7 Reverse",
      start: 2497,
      type: "primer_bind",
    },
    {
      direction: 1,
      end: 2559,
      name: "T7 terminator",
      start: 2511,
      type: "terminator",
    },
    {
      direction: -1,
      end: 2580,
      name: "M13 rev",
      start: 2559,
      type: "primer_bind",
    },
    {
      direction: 1,
      end: 2595,
      name: "AarI",
      start: 2580,
      type: "misc_feature",
    },
    {
      direction: 1,
      end: 2646,
      name: "spacer",
      start: 2595,
      type: "misc_feature",
    },
  ],
  name: "plamGFP-PURE",
  seq: "taactatcgtcttgagtccaacccggtaagacacgacttatcgccactggcagcagccactggtaacaggattagcagagcgaggtatgtaggcggtgctacagagttcttgaagtggtggcctaactacggctacactagaagaacagtatttggtatctgcgctctgctgaagccagttaccttcggaaaaagagttggtagctcttgatccggcaaacaaaccaccgctggtagcggtggtttttttgtttgcaagcagcagattacgcgcagaaaaaaaggatctcaagaaggcctactattagcaacaacgatcctttgatcttttctacggggtctgacgctcagtggaacgaaaactcacgttaagggattttggtcatgagattatcaaaaaggatcttcacctagatccttttaaattaaaaatgaagttttaaatcaatctaaagtatatatgagtaaacttggtctgacagttaccaatgcttaatcagtgaggcacctatctcagcgatctgtctatttcgttcatccatagttgcctgactccccgtcgtgtagataactacgatacgggagggcttaccatctggccccagtgctgcaatgataccgcgagaaccacgctcaccggctccagatttatcagcaataaaccagccagccggaagggccgagcgcagaagtggtcctgcaactttatccgcctccatccagtctattaattgttgccgggaagctagagtaagtagttcgccagttaatagtttgcgcaacgttgttgccattgctacaggcatcgtggtgtcacgctcgtcgtttggtatggcttcattcagctccggttcccaacgatcaaggcgagttacatgatcccccatgttgtgcaaaaaagcggttagctccttcggtcctccgatcgttgtcagaagtaagttggccgcagtgttatcactcatggttatggcagcactgcataattctcttactgtcatgccatccgtaagatgcttttctgtgactggtgagtactcaaccaagtcattctgagaatagtgtatgcggcgaccgagttgctcttgcccggcgtcaatacgggataataccgcgccacatagcagaactttaaaagtgctcatcattggaaaacgttcttcggggcgaaaactctcaaggatcttaccgctgttgagatccagttcgatgtaacccactcgtgcacccaactgatcttcagcatcttttactttcaccagcgtttctgggtgagcaaaaacaggaaggcaaaatgccgcaaaaaagggaataagggcgacacggaaatgttgaatactcatactcttcctttttcaatattattgaagcatttatcagggttattgtctcatgagcggatacatatttgaatgtatttagaaaaataaacaaataggggttccgcgcacctgcaccagtcagtaaaacgacggccagtagtcaaaagcctccgaccggaggcttttgacttggttcaggtggagtgggaggagtttgtcggtcgggtccctagggataacagggtaatcgcgatacaggctgcaacccagattagctgccgatactggcgtctcataactaatacgactcactatagggaataattttgtttaactttaagaaggagggtctctaatggagatcgaggatgtgatcaaacgcgacatgaaaatcaagctgcgtatggaaggtgctgttaacggtcacaaattcgtgatcattggtaacggcgacggcaaaccatatgaaggcactcagaccatcgatctggaagtcattgaaggtgccccgctgccgttcgcatttgacatcctgactacagtttttgaatacggtaacagagttttcgccaaatatccgaacgaaattgttgactacttcaaacaatcctttccggagggctactcttgggagcgttctatgacctacgaggacggcggcatttgtatcgccaccaacaatatcaccctgtccaaagtaatcgataactgcttccattacaacatccgtttcgatggggtgaatttcccgccgaaaagcccggtgcttcagaaaaccaccatgaaatgggaaccgtccaccgaaatcatgtacgttcgtgacggtgtgctgaaaggcgacgtaaacatggccctgctgatcgaaggcggtggtcattatcgttgcgattttaaaacgatctacaaagcgaaaaaagttgttgaactgccggactatcactttgtcgaccaccgtatcaccattaaatcacacgacaaagactacaacaaagtcctgcttcacgaacacgcaaaagcccgttacggcctccagcgtaaagcgaagtgaagagcttagagaccgagataacagatacttcggtatctgttatctgttttttttggagtgagacgaaacacgtggcaaacattcctctgggggatgaatcatggtgctgaggtgtcaatcgtcggagccgctgagcaataactagcataaccccttggggcctctaaacgggtcttgaggggttttttgcatggtcatagctgtttcctgagagcttggcaggtgatgacacacattaacaaatttcgtgaggagtctccagaagaatgccattaatttccataggctccgcccccctgacgagcatcacaaaaatcgacgctcaagtcagaggtggcgaaacccgacaggactataaagataccaggcgtttccccctggaagctccctcgtgcgctctcctgttccgaccctgccgcttaccggatacctgtccgcctttctcccttcgggaagcgtggcgctttctcatagctcacgctgtaggtatctcagttcggtgtaggtcgttcgctccaagctgggctgtgtgcacgaaccccccgttcagcccgaccgctgcgccttatccgg",
  type: "dna",
});

render({ model: fromFile, el: document.getElementById("widget-container")! });
